package libvirt

import "fmt"

const _s_name = "VIR_DOMAIN_NOSTATEVIR_DOMAIN_RUNNINGVIR_DOMAIN_BLOCKEDVIR_DOMAIN_PAUSEDVIR_DOMAIN_SHUTDOWNVIR_DOMAIN_CRASHEDVIR_DOMAIN_PMSUSPENDEDVIR_DOMAIN_SHUTOFFVIR_VCPU_OFFLINEVIR_VCPU_RUNNINGVIR_VCPU_BLOCKEDVIR_CONNECT_LIST_DOMAINS_ACTIVEVIR_CONNECT_LIST_DOMAINS_INACTIVEVIR_CONNECT_LIST_DOMAINS_PERSISTENTVIR_CONNECT_LIST_DOMAINS_TRANSIENTVIR_CONNECT_LIST_DOMAINS_RUNNINGVIR_CONNECT_LIST_DOMAINS_PAUSEDVIR_CONNECT_LIST_DOMAINS_SHUTOFFVIR_CONNECT_LIST_DOMAINS_OTHERVIR_CONNECT_LIST_DOMAINS_MANAGEDSAVEVIR_CONNECT_LIST_DOMAINS_NO_MANAGEDSAVEVIR_CONNECT_LIST_DOMAINS_AUTOSTARTVIR_CONNECT_LIST_DOMAINS_NO_AUTOSTARTVIR_CONNECT_LIST_DOMAINS_HAS_SNAPSHOTVIR_CONNECT_LIST_DOMAINS_NO_SNAPSHOTVIR_DOMAIN_METADATA_DESCRIPTIONVIR_DOMAIN_METADATA_TITLEVIR_DOMAIN_METADATA_ELEMENTVIR_DOMAIN_VCPU_CONFIGVIR_DOMAIN_VCPU_CURRENTVIR_DOMAIN_VCPU_LIVEVIR_DOMAIN_VCPU_MAXIMUMVIR_DOMAIN_VCPU_GUESTVIR_DOMAIN_AFFECT_CONFIGVIR_DOMAIN_AFFECT_CURRENTVIR_DOMAIN_AFFECT_LIVEVIR_DOMAIN_MEM_CONFIGVIR_DOMAIN_MEM_CURRENTVIR_DOMAIN_MEM_LIVEVIR_DOMAIN_MEM_MAXIMUMVIR_STORAGE_POOL_INACTIVEVIR_STORAGE_POOL_BUILDINGVIR_STORAGE_POOL_RUNNINGVIR_STORAGE_POOL_DEGRADEDVIR_STORAGE_POOL_INACCESSIBLEVIR_STORAGE_POOL_BUILD_NEWVIR_STORAGE_POOL_BUILD_REPAIRVIR_STORAGE_POOL_BUILD_RESIZEVIR_STORAGE_POOL_BUILD_NO_OVERWRITEVIR_STORAGE_POOL_BUILD_OVERWRITEVIR_DOMAIN_DESTROY_DEFAULTVIR_DOMAIN_DESTROY_GRACEFULVIR_DOMAIN_SHUTDOWN_DEFAULTVIR_DOMAIN_SHUTDOWN_ACPI_POWER_BTNVIR_DOMAIN_SHUTDOWN_GUEST_AGENTVIR_DOMAIN_SHUTDOWN_INITCTLVIR_DOMAIN_SHUTDOWN_SIGNALVIR_DOMAIN_DEVICE_MODIFY_CONFIGVIR_DOMAIN_DEVICE_MODIFY_CURRENTVIR_DOMAIN_DEVICE_MODIFY_LIVEVIR_DOMAIN_DEVICE_MODIFY_FORCEVIR_STORAGE_VOL_CREATE_PREALLOC_METADATAVIR_STORAGE_VOL_DELETE_NORMALVIR_STORAGE_VOL_DELETE_ZEROEDVIR_STORAGE_VOL_RESIZE_ALLOCATEVIR_STORAGE_VOL_RESIZE_DELTAVIR_STORAGE_VOL_RESIZE_SHRINKVIR_STORAGE_VOL_FILEVIR_STORAGE_VOL_BLOCKVIR_STORAGE_VOL_DIRVIR_STORAGE_VOL_NETWORKVIR_STORAGE_VOL_NETDIRVIR_STORAGE_VOL_WIPE_ALG_ZEROVIR_STORAGE_VOL_WIPE_ALG_NNSAVIR_STORAGE_VOL_WIPE_ALG_DODVIR_STORAGE_VOL_WIPE_ALG_BSIVIR_STORAGE_VOL_WIPE_ALG_GUTMANNVIR_STORAGE_VOL_WIPE_ALG_SCHNEIERVIR_STORAGE_VOL_WIPE_ALG_PFITZNER7VIR_STORAGE_VOL_WIPE_ALG_PFITZNER33VIR_STORAGE_VOL_WIPE_ALG_RANDOMVIR_SECRET_USAGE_TYPE_NONEVIR_SECRET_USAGE_TYPE_VOLUMEVIR_SECRET_USAGE_TYPE_CEPHVIR_SECRET_USAGE_TYPE_ISCSIVIR_CONNECT_LIST_NETWORKS_INACTIVEVIR_CONNECT_LIST_NETWORKS_ACTIVEVIR_CONNECT_LIST_NETWORKS_PERSISTENTVIR_CONNECT_LIST_NETWORKS_TRANSIENTVIR_CONNECT_LIST_NETWORKS_AUTOSTARTVIR_CONNECT_LIST_NETWORKS_NO_AUTOSTARTVIR_CONNECT_LIST_STORAGE_POOLS_INACTIVEVIR_CONNECT_LIST_STORAGE_POOLS_ACTIVEVIR_CONNECT_LIST_STORAGE_POOLS_PERSISTENTVIR_CONNECT_LIST_STORAGE_POOLS_TRANSIENTVIR_CONNECT_LIST_STORAGE_POOLS_AUTOSTARTVIR_CONNECT_LIST_STORAGE_POOLS_NO_AUTOSTARTVIR_CONNECT_LIST_STORAGE_POOLS_DIRVIR_CONNECT_LIST_STORAGE_POOLS_FSVIR_CONNECT_LIST_STORAGE_POOLS_NETFSVIR_CONNECT_LIST_STORAGE_POOLS_LOGICALVIR_CONNECT_LIST_STORAGE_POOLS_DISKVIR_CONNECT_LIST_STORAGE_POOLS_ISCSIVIR_CONNECT_LIST_STORAGE_POOLS_SCSIVIR_CONNECT_LIST_STORAGE_POOLS_MPATHVIR_CONNECT_LIST_STORAGE_POOLS_RBDVIR_CONNECT_LIST_STORAGE_POOLS_SHEEPDOGVIR_CONNECT_LIST_STORAGE_POOLS_GLUSTERVIR_STREAM_NONBLOCKVIR_KEYCODE_SET_LINUXVIR_KEYCODE_SET_XTVIR_KEYCODE_SET_ATSET1VIR_KEYCODE_SET_ATSET2VIR_KEYCODE_SET_ATSET3VIR_KEYCODE_SET_OSXVIR_KEYCODE_SET_XT_KBDVIR_KEYCODE_SET_USBVIR_KEYCODE_SET_WIN32VIR_KEYCODE_SET_RFBVIR_DOMAIN_NONEVIR_DOMAIN_START_PAUSEDVIR_DOMAIN_START_AUTODESTROYVIR_DOMAIN_START_BYPASS_CACHEVIR_DOMAIN_START_FORCE_BOOTVIR_DOMAIN_MEMORY_PARAM_UNLIMITEDVIR_DOMAIN_EVENT_ID_LIFECYCLEVIR_DOMAIN_EVENT_ID_REBOOTVIR_DOMAIN_EVENT_ID_RTC_CHANGEVIR_DOMAIN_EVENT_ID_WATCHDOGVIR_DOMAIN_EVENT_ID_IO_ERRORVIR_DOMAIN_EVENT_ID_GRAPHICSVIR_DOMAIN_EVENT_ID_IO_ERROR_REASONVIR_DOMAIN_EVENT_ID_CONTROL_ERRORVIR_DOMAIN_EVENT_ID_BLOCK_JOBVIR_DOMAIN_EVENT_ID_DISK_CHANGEVIR_DOMAIN_EVENT_ID_TRAY_CHANGEVIR_DOMAIN_EVENT_ID_PMWAKEUPVIR_DOMAIN_EVENT_ID_PMSUSPENDVIR_DOMAIN_EVENT_ID_BALLOON_CHANGEVIR_DOMAIN_EVENT_ID_PMSUSPEND_DISKVIR_DOMAIN_EVENT_ID_DEVICE_REMOVEDVIR_DOMAIN_EVENT_DEFINEDVIR_DOMAIN_EVENT_UNDEFINEDVIR_DOMAIN_EVENT_STARTEDVIR_DOMAIN_EVENT_SUSPENDEDVIR_DOMAIN_EVENT_RESUMEDVIR_DOMAIN_EVENT_STOPPEDVIR_DOMAIN_EVENT_SHUTDOWNVIR_DOMAIN_EVENT_PMSUSPENDEDVIR_DOMAIN_EVENT_CRASHEDVIR_DOMAIN_EVENT_WATCHDOG_NONEVIR_DOMAIN_EVENT_WATCHDOG_PAUSEVIR_DOMAIN_EVENT_WATCHDOG_RESETVIR_DOMAIN_EVENT_WATCHDOG_POWEROFFVIR_DOMAIN_EVENT_WATCHDOG_SHUTDOWNVIR_DOMAIN_EVENT_WATCHDOG_DEBUGVIR_DOMAIN_EVENT_IO_ERROR_NONEVIR_DOMAIN_EVENT_IO_ERROR_PAUSEVIR_DOMAIN_EVENT_IO_ERROR_REPORTVIR_DOMAIN_EVENT_GRAPHICS_CONNECTVIR_DOMAIN_EVENT_GRAPHICS_INITIALIZEVIR_DOMAIN_EVENT_GRAPHICS_DISCONNECTVIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV4VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV6VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_UNIXVIR_DOMAIN_BLOCK_JOB_TYPE_UNKNOWNVIR_DOMAIN_BLOCK_JOB_TYPE_PULLVIR_DOMAIN_BLOCK_JOB_TYPE_COPYVIR_DOMAIN_BLOCK_JOB_TYPE_COMMITVIR_DOMAIN_BLOCK_JOB_COMPLETEDVIR_DOMAIN_BLOCK_JOB_FAILEDVIR_DOMAIN_BLOCK_JOB_CANCELEDVIR_DOMAIN_BLOCK_JOB_READYVIR_DOMAIN_EVENT_DISK_CHANGE_MISSING_ON_STARTVIR_DOMAIN_EVENT_DISK_DROP_MISSING_ON_STARTVIR_DOMAIN_EVENT_TRAY_CHANGE_OPENVIR_DOMAIN_EVENT_TRAY_CHANGE_CLOSEVIR_DOMAIN_RUNNING_UNKNOWNVIR_DOMAIN_RUNNING_BOOTEDVIR_DOMAIN_RUNNING_MIGRATEDVIR_DOMAIN_RUNNING_RESTOREDVIR_DOMAIN_RUNNING_FROM_SNAPSHOTVIR_DOMAIN_RUNNING_UNPAUSEDVIR_DOMAIN_RUNNING_MIGRATION_CANCELEDVIR_DOMAIN_RUNNING_SAVE_CANCELEDVIR_DOMAIN_RUNNING_WAKEUPVIR_DOMAIN_RUNNING_CRASHEDVIR_DOMAIN_PAUSED_UNKNOWNVIR_DOMAIN_PAUSED_USERVIR_DOMAIN_PAUSED_MIGRATIONVIR_DOMAIN_PAUSED_SAVEVIR_DOMAIN_PAUSED_DUMPVIR_DOMAIN_PAUSED_IOERRORVIR_DOMAIN_PAUSED_WATCHDOGVIR_DOMAIN_PAUSED_FROM_SNAPSHOTVIR_DOMAIN_PAUSED_SHUTTING_DOWNVIR_DOMAIN_PAUSED_SNAPSHOTVIR_DOMAIN_PAUSED_CRASHEDVIR_DOMAIN_XML_SECUREVIR_DOMAIN_XML_INACTIVEVIR_DOMAIN_XML_UPDATE_CPUVIR_DOMAIN_XML_MIGRATABLEVIR_DOMAIN_QEMU_MONITOR_COMMAND_DEFAULTVIR_DOMAIN_QEMU_MONITOR_COMMAND_HMPVIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASEVIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENTVIR_IP_ADDR_TYPE_IPV4VIR_IP_ADDR_TYPE_IPV6"

var _VIR_DOMAIN_NOSTATE_INT = int(VIR_DOMAIN_NOSTATE)
var _VIR_DOMAIN_RUNNING_INT = int(VIR_DOMAIN_RUNNING)
var _VIR_DOMAIN_BLOCKED_INT = int(VIR_DOMAIN_BLOCKED)
var _VIR_DOMAIN_PAUSED_INT = int(VIR_DOMAIN_PAUSED)
var _VIR_DOMAIN_SHUTDOWN_INT = int(VIR_DOMAIN_SHUTDOWN)
var _VIR_DOMAIN_CRASHED_INT = int(VIR_DOMAIN_CRASHED)
var _VIR_DOMAIN_PMSUSPENDED_INT = int(VIR_DOMAIN_PMSUSPENDED)
var _VIR_DOMAIN_SHUTOFF_INT = int(VIR_DOMAIN_SHUTOFF)
var _VIR_VCPU_OFFLINE_INT = int(VIR_VCPU_OFFLINE)
var _VIR_VCPU_RUNNING_INT = int(VIR_VCPU_RUNNING)
var _VIR_VCPU_BLOCKED_INT = int(VIR_VCPU_BLOCKED)
var _VIR_CONNECT_LIST_DOMAINS_ACTIVE_INT = int(VIR_CONNECT_LIST_DOMAINS_ACTIVE)
var _VIR_CONNECT_LIST_DOMAINS_INACTIVE_INT = int(VIR_CONNECT_LIST_DOMAINS_INACTIVE)
var _VIR_CONNECT_LIST_DOMAINS_PERSISTENT_INT = int(VIR_CONNECT_LIST_DOMAINS_PERSISTENT)
var _VIR_CONNECT_LIST_DOMAINS_TRANSIENT_INT = int(VIR_CONNECT_LIST_DOMAINS_TRANSIENT)
var _VIR_CONNECT_LIST_DOMAINS_RUNNING_INT = int(VIR_CONNECT_LIST_DOMAINS_RUNNING)
var _VIR_CONNECT_LIST_DOMAINS_PAUSED_INT = int(VIR_CONNECT_LIST_DOMAINS_PAUSED)
var _VIR_CONNECT_LIST_DOMAINS_SHUTOFF_INT = int(VIR_CONNECT_LIST_DOMAINS_SHUTOFF)
var _VIR_CONNECT_LIST_DOMAINS_OTHER_INT = int(VIR_CONNECT_LIST_DOMAINS_OTHER)
var _VIR_CONNECT_LIST_DOMAINS_MANAGEDSAVE_INT = int(VIR_CONNECT_LIST_DOMAINS_MANAGEDSAVE)
var _VIR_CONNECT_LIST_DOMAINS_NO_MANAGEDSAVE_INT = int(VIR_CONNECT_LIST_DOMAINS_NO_MANAGEDSAVE)
var _VIR_CONNECT_LIST_DOMAINS_AUTOSTART_INT = int(VIR_CONNECT_LIST_DOMAINS_AUTOSTART)
var _VIR_CONNECT_LIST_DOMAINS_NO_AUTOSTART_INT = int(VIR_CONNECT_LIST_DOMAINS_NO_AUTOSTART)
var _VIR_CONNECT_LIST_DOMAINS_HAS_SNAPSHOT_INT = int(VIR_CONNECT_LIST_DOMAINS_HAS_SNAPSHOT)
var _VIR_CONNECT_LIST_DOMAINS_NO_SNAPSHOT_INT = int(VIR_CONNECT_LIST_DOMAINS_NO_SNAPSHOT)
var _VIR_DOMAIN_METADATA_DESCRIPTION_INT = int(VIR_DOMAIN_METADATA_DESCRIPTION)
var _VIR_DOMAIN_METADATA_TITLE_INT = int(VIR_DOMAIN_METADATA_TITLE)
var _VIR_DOMAIN_METADATA_ELEMENT_INT = int(VIR_DOMAIN_METADATA_ELEMENT)
var _VIR_DOMAIN_VCPU_CONFIG_INT = int(VIR_DOMAIN_VCPU_CONFIG)
var _VIR_DOMAIN_VCPU_CURRENT_INT = int(VIR_DOMAIN_VCPU_CURRENT)
var _VIR_DOMAIN_VCPU_LIVE_INT = int(VIR_DOMAIN_VCPU_LIVE)
var _VIR_DOMAIN_VCPU_MAXIMUM_INT = int(VIR_DOMAIN_VCPU_MAXIMUM)
var _VIR_DOMAIN_VCPU_GUEST_INT = int(VIR_DOMAIN_VCPU_GUEST)
var _VIR_DOMAIN_AFFECT_CONFIG_INT = int(VIR_DOMAIN_AFFECT_CONFIG)
var _VIR_DOMAIN_AFFECT_CURRENT_INT = int(VIR_DOMAIN_AFFECT_CURRENT)
var _VIR_DOMAIN_AFFECT_LIVE_INT = int(VIR_DOMAIN_AFFECT_LIVE)
var _VIR_DOMAIN_MEM_CONFIG_INT = int(VIR_DOMAIN_MEM_CONFIG)
var _VIR_DOMAIN_MEM_CURRENT_INT = int(VIR_DOMAIN_MEM_CURRENT)
var _VIR_DOMAIN_MEM_LIVE_INT = int(VIR_DOMAIN_MEM_LIVE)
var _VIR_DOMAIN_MEM_MAXIMUM_INT = int(VIR_DOMAIN_MEM_MAXIMUM)
var _VIR_STORAGE_POOL_INACTIVE_INT = int(VIR_STORAGE_POOL_INACTIVE)
var _VIR_STORAGE_POOL_BUILDING_INT = int(VIR_STORAGE_POOL_BUILDING)
var _VIR_STORAGE_POOL_RUNNING_INT = int(VIR_STORAGE_POOL_RUNNING)
var _VIR_STORAGE_POOL_DEGRADED_INT = int(VIR_STORAGE_POOL_DEGRADED)
var _VIR_STORAGE_POOL_INACCESSIBLE_INT = int(VIR_STORAGE_POOL_INACCESSIBLE)
var _VIR_STORAGE_POOL_BUILD_NEW_INT = int(VIR_STORAGE_POOL_BUILD_NEW)
var _VIR_STORAGE_POOL_BUILD_REPAIR_INT = int(VIR_STORAGE_POOL_BUILD_REPAIR)
var _VIR_STORAGE_POOL_BUILD_RESIZE_INT = int(VIR_STORAGE_POOL_BUILD_RESIZE)
var _VIR_STORAGE_POOL_BUILD_NO_OVERWRITE_INT = int(VIR_STORAGE_POOL_BUILD_NO_OVERWRITE)
var _VIR_STORAGE_POOL_BUILD_OVERWRITE_INT = int(VIR_STORAGE_POOL_BUILD_OVERWRITE)
var _VIR_DOMAIN_DESTROY_DEFAULT_INT = int(VIR_DOMAIN_DESTROY_DEFAULT)
var _VIR_DOMAIN_DESTROY_GRACEFUL_INT = int(VIR_DOMAIN_DESTROY_GRACEFUL)
var _VIR_DOMAIN_SHUTDOWN_DEFAULT_INT = int(VIR_DOMAIN_SHUTDOWN_DEFAULT)
var _VIR_DOMAIN_SHUTDOWN_ACPI_POWER_BTN_INT = int(VIR_DOMAIN_SHUTDOWN_ACPI_POWER_BTN)
var _VIR_DOMAIN_SHUTDOWN_GUEST_AGENT_INT = int(VIR_DOMAIN_SHUTDOWN_GUEST_AGENT)
var _VIR_DOMAIN_SHUTDOWN_INITCTL_INT = int(VIR_DOMAIN_SHUTDOWN_INITCTL)
var _VIR_DOMAIN_SHUTDOWN_SIGNAL_INT = int(VIR_DOMAIN_SHUTDOWN_SIGNAL)
var _VIR_DOMAIN_DEVICE_MODIFY_CONFIG_INT = int(VIR_DOMAIN_DEVICE_MODIFY_CONFIG)
var _VIR_DOMAIN_DEVICE_MODIFY_CURRENT_INT = int(VIR_DOMAIN_DEVICE_MODIFY_CURRENT)
var _VIR_DOMAIN_DEVICE_MODIFY_LIVE_INT = int(VIR_DOMAIN_DEVICE_MODIFY_LIVE)
var _VIR_DOMAIN_DEVICE_MODIFY_FORCE_INT = int(VIR_DOMAIN_DEVICE_MODIFY_FORCE)
var _VIR_STORAGE_VOL_CREATE_PREALLOC_METADATA_INT = int(VIR_STORAGE_VOL_CREATE_PREALLOC_METADATA)
var _VIR_STORAGE_VOL_DELETE_NORMAL_INT = int(VIR_STORAGE_VOL_DELETE_NORMAL)
var _VIR_STORAGE_VOL_DELETE_ZEROED_INT = int(VIR_STORAGE_VOL_DELETE_ZEROED)
var _VIR_STORAGE_VOL_RESIZE_ALLOCATE_INT = int(VIR_STORAGE_VOL_RESIZE_ALLOCATE)
var _VIR_STORAGE_VOL_RESIZE_DELTA_INT = int(VIR_STORAGE_VOL_RESIZE_DELTA)
var _VIR_STORAGE_VOL_RESIZE_SHRINK_INT = int(VIR_STORAGE_VOL_RESIZE_SHRINK)
var _VIR_STORAGE_VOL_FILE_INT = int(VIR_STORAGE_VOL_FILE)
var _VIR_STORAGE_VOL_BLOCK_INT = int(VIR_STORAGE_VOL_BLOCK)
var _VIR_STORAGE_VOL_DIR_INT = int(VIR_STORAGE_VOL_DIR)
var _VIR_STORAGE_VOL_NETWORK_INT = int(VIR_STORAGE_VOL_NETWORK)
var _VIR_STORAGE_VOL_NETDIR_INT = int(VIR_STORAGE_VOL_NETDIR)
var _VIR_STORAGE_VOL_WIPE_ALG_ZERO_INT = int(VIR_STORAGE_VOL_WIPE_ALG_ZERO)
var _VIR_STORAGE_VOL_WIPE_ALG_NNSA_INT = int(VIR_STORAGE_VOL_WIPE_ALG_NNSA)
var _VIR_STORAGE_VOL_WIPE_ALG_DOD_INT = int(VIR_STORAGE_VOL_WIPE_ALG_DOD)
var _VIR_STORAGE_VOL_WIPE_ALG_BSI_INT = int(VIR_STORAGE_VOL_WIPE_ALG_BSI)
var _VIR_STORAGE_VOL_WIPE_ALG_GUTMANN_INT = int(VIR_STORAGE_VOL_WIPE_ALG_GUTMANN)
var _VIR_STORAGE_VOL_WIPE_ALG_SCHNEIER_INT = int(VIR_STORAGE_VOL_WIPE_ALG_SCHNEIER)
var _VIR_STORAGE_VOL_WIPE_ALG_PFITZNER7_INT = int(VIR_STORAGE_VOL_WIPE_ALG_PFITZNER7)
var _VIR_STORAGE_VOL_WIPE_ALG_PFITZNER33_INT = int(VIR_STORAGE_VOL_WIPE_ALG_PFITZNER33)
var _VIR_STORAGE_VOL_WIPE_ALG_RANDOM_INT = int(VIR_STORAGE_VOL_WIPE_ALG_RANDOM)
var _VIR_SECRET_USAGE_TYPE_NONE_INT = int(VIR_SECRET_USAGE_TYPE_NONE)
var _VIR_SECRET_USAGE_TYPE_VOLUME_INT = int(VIR_SECRET_USAGE_TYPE_VOLUME)
var _VIR_SECRET_USAGE_TYPE_CEPH_INT = int(VIR_SECRET_USAGE_TYPE_CEPH)
var _VIR_SECRET_USAGE_TYPE_ISCSI_INT = int(VIR_SECRET_USAGE_TYPE_ISCSI)
var _VIR_CONNECT_LIST_NETWORKS_INACTIVE_INT = int(VIR_CONNECT_LIST_NETWORKS_INACTIVE)
var _VIR_CONNECT_LIST_NETWORKS_ACTIVE_INT = int(VIR_CONNECT_LIST_NETWORKS_ACTIVE)
var _VIR_CONNECT_LIST_NETWORKS_PERSISTENT_INT = int(VIR_CONNECT_LIST_NETWORKS_PERSISTENT)
var _VIR_CONNECT_LIST_NETWORKS_TRANSIENT_INT = int(VIR_CONNECT_LIST_NETWORKS_TRANSIENT)
var _VIR_CONNECT_LIST_NETWORKS_AUTOSTART_INT = int(VIR_CONNECT_LIST_NETWORKS_AUTOSTART)
var _VIR_CONNECT_LIST_NETWORKS_NO_AUTOSTART_INT = int(VIR_CONNECT_LIST_NETWORKS_NO_AUTOSTART)
var _VIR_CONNECT_LIST_STORAGE_POOLS_INACTIVE_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_INACTIVE)
var _VIR_CONNECT_LIST_STORAGE_POOLS_ACTIVE_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_ACTIVE)
var _VIR_CONNECT_LIST_STORAGE_POOLS_PERSISTENT_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_PERSISTENT)
var _VIR_CONNECT_LIST_STORAGE_POOLS_TRANSIENT_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_TRANSIENT)
var _VIR_CONNECT_LIST_STORAGE_POOLS_AUTOSTART_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_AUTOSTART)
var _VIR_CONNECT_LIST_STORAGE_POOLS_NO_AUTOSTART_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_NO_AUTOSTART)
var _VIR_CONNECT_LIST_STORAGE_POOLS_DIR_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_DIR)
var _VIR_CONNECT_LIST_STORAGE_POOLS_FS_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_FS)
var _VIR_CONNECT_LIST_STORAGE_POOLS_NETFS_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_NETFS)
var _VIR_CONNECT_LIST_STORAGE_POOLS_LOGICAL_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_LOGICAL)
var _VIR_CONNECT_LIST_STORAGE_POOLS_DISK_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_DISK)
var _VIR_CONNECT_LIST_STORAGE_POOLS_ISCSI_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_ISCSI)
var _VIR_CONNECT_LIST_STORAGE_POOLS_SCSI_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_SCSI)
var _VIR_CONNECT_LIST_STORAGE_POOLS_MPATH_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_MPATH)
var _VIR_CONNECT_LIST_STORAGE_POOLS_RBD_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_RBD)
var _VIR_CONNECT_LIST_STORAGE_POOLS_SHEEPDOG_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_SHEEPDOG)
var _VIR_CONNECT_LIST_STORAGE_POOLS_GLUSTER_INT = int(VIR_CONNECT_LIST_STORAGE_POOLS_GLUSTER)
var _VIR_STREAM_NONBLOCK_INT = int(VIR_STREAM_NONBLOCK)
var _VIR_KEYCODE_SET_LINUX_INT = int(VIR_KEYCODE_SET_LINUX)
var _VIR_KEYCODE_SET_XT_INT = int(VIR_KEYCODE_SET_XT)
var _VIR_KEYCODE_SET_ATSET1_INT = int(VIR_KEYCODE_SET_ATSET1)
var _VIR_KEYCODE_SET_ATSET2_INT = int(VIR_KEYCODE_SET_ATSET2)
var _VIR_KEYCODE_SET_ATSET3_INT = int(VIR_KEYCODE_SET_ATSET3)
var _VIR_KEYCODE_SET_OSX_INT = int(VIR_KEYCODE_SET_OSX)
var _VIR_KEYCODE_SET_XT_KBD_INT = int(VIR_KEYCODE_SET_XT_KBD)
var _VIR_KEYCODE_SET_USB_INT = int(VIR_KEYCODE_SET_USB)
var _VIR_KEYCODE_SET_WIN32_INT = int(VIR_KEYCODE_SET_WIN32)
var _VIR_KEYCODE_SET_RFB_INT = int(VIR_KEYCODE_SET_RFB)
var _VIR_DOMAIN_NONE_INT = int(VIR_DOMAIN_NONE)
var _VIR_DOMAIN_START_PAUSED_INT = int(VIR_DOMAIN_START_PAUSED)
var _VIR_DOMAIN_START_AUTODESTROY_INT = int(VIR_DOMAIN_START_AUTODESTROY)
var _VIR_DOMAIN_START_BYPASS_CACHE_INT = int(VIR_DOMAIN_START_BYPASS_CACHE)
var _VIR_DOMAIN_START_FORCE_BOOT_INT = int(VIR_DOMAIN_START_FORCE_BOOT)
var _VIR_DOMAIN_MEMORY_PARAM_UNLIMITED_INT = int(VIR_DOMAIN_MEMORY_PARAM_UNLIMITED)
var _VIR_DOMAIN_EVENT_ID_LIFECYCLE_INT = int(VIR_DOMAIN_EVENT_ID_LIFECYCLE)
var _VIR_DOMAIN_EVENT_ID_REBOOT_INT = int(VIR_DOMAIN_EVENT_ID_REBOOT)
var _VIR_DOMAIN_EVENT_ID_RTC_CHANGE_INT = int(VIR_DOMAIN_EVENT_ID_RTC_CHANGE)
var _VIR_DOMAIN_EVENT_ID_WATCHDOG_INT = int(VIR_DOMAIN_EVENT_ID_WATCHDOG)
var _VIR_DOMAIN_EVENT_ID_IO_ERROR_INT = int(VIR_DOMAIN_EVENT_ID_IO_ERROR)
var _VIR_DOMAIN_EVENT_ID_GRAPHICS_INT = int(VIR_DOMAIN_EVENT_ID_GRAPHICS)
var _VIR_DOMAIN_EVENT_ID_IO_ERROR_REASON_INT = int(VIR_DOMAIN_EVENT_ID_IO_ERROR_REASON)
var _VIR_DOMAIN_EVENT_ID_CONTROL_ERROR_INT = int(VIR_DOMAIN_EVENT_ID_CONTROL_ERROR)
var _VIR_DOMAIN_EVENT_ID_BLOCK_JOB_INT = int(VIR_DOMAIN_EVENT_ID_BLOCK_JOB)
var _VIR_DOMAIN_EVENT_ID_DISK_CHANGE_INT = int(VIR_DOMAIN_EVENT_ID_DISK_CHANGE)
var _VIR_DOMAIN_EVENT_ID_TRAY_CHANGE_INT = int(VIR_DOMAIN_EVENT_ID_TRAY_CHANGE)
var _VIR_DOMAIN_EVENT_ID_PMWAKEUP_INT = int(VIR_DOMAIN_EVENT_ID_PMWAKEUP)
var _VIR_DOMAIN_EVENT_ID_PMSUSPEND_INT = int(VIR_DOMAIN_EVENT_ID_PMSUSPEND)
var _VIR_DOMAIN_EVENT_ID_BALLOON_CHANGE_INT = int(VIR_DOMAIN_EVENT_ID_BALLOON_CHANGE)
var _VIR_DOMAIN_EVENT_ID_PMSUSPEND_DISK_INT = int(VIR_DOMAIN_EVENT_ID_PMSUSPEND_DISK)
var _VIR_DOMAIN_EVENT_ID_DEVICE_REMOVED_INT = int(VIR_DOMAIN_EVENT_ID_DEVICE_REMOVED)
var _VIR_DOMAIN_EVENT_DEFINED_INT = int(VIR_DOMAIN_EVENT_DEFINED)
var _VIR_DOMAIN_EVENT_UNDEFINED_INT = int(VIR_DOMAIN_EVENT_UNDEFINED)
var _VIR_DOMAIN_EVENT_STARTED_INT = int(VIR_DOMAIN_EVENT_STARTED)
var _VIR_DOMAIN_EVENT_SUSPENDED_INT = int(VIR_DOMAIN_EVENT_SUSPENDED)
var _VIR_DOMAIN_EVENT_RESUMED_INT = int(VIR_DOMAIN_EVENT_RESUMED)
var _VIR_DOMAIN_EVENT_STOPPED_INT = int(VIR_DOMAIN_EVENT_STOPPED)
var _VIR_DOMAIN_EVENT_SHUTDOWN_INT = int(VIR_DOMAIN_EVENT_SHUTDOWN)
var _VIR_DOMAIN_EVENT_PMSUSPENDED_INT = int(VIR_DOMAIN_EVENT_PMSUSPENDED)
var _VIR_DOMAIN_EVENT_CRASHED_INT = int(VIR_DOMAIN_EVENT_CRASHED)
var _VIR_DOMAIN_EVENT_WATCHDOG_NONE_INT = int(VIR_DOMAIN_EVENT_WATCHDOG_NONE)
var _VIR_DOMAIN_EVENT_WATCHDOG_PAUSE_INT = int(VIR_DOMAIN_EVENT_WATCHDOG_PAUSE)
var _VIR_DOMAIN_EVENT_WATCHDOG_RESET_INT = int(VIR_DOMAIN_EVENT_WATCHDOG_RESET)
var _VIR_DOMAIN_EVENT_WATCHDOG_POWEROFF_INT = int(VIR_DOMAIN_EVENT_WATCHDOG_POWEROFF)
var _VIR_DOMAIN_EVENT_WATCHDOG_SHUTDOWN_INT = int(VIR_DOMAIN_EVENT_WATCHDOG_SHUTDOWN)
var _VIR_DOMAIN_EVENT_WATCHDOG_DEBUG_INT = int(VIR_DOMAIN_EVENT_WATCHDOG_DEBUG)
var _VIR_DOMAIN_EVENT_IO_ERROR_NONE_INT = int(VIR_DOMAIN_EVENT_IO_ERROR_NONE)
var _VIR_DOMAIN_EVENT_IO_ERROR_PAUSE_INT = int(VIR_DOMAIN_EVENT_IO_ERROR_PAUSE)
var _VIR_DOMAIN_EVENT_IO_ERROR_REPORT_INT = int(VIR_DOMAIN_EVENT_IO_ERROR_REPORT)
var _VIR_DOMAIN_EVENT_GRAPHICS_CONNECT_INT = int(VIR_DOMAIN_EVENT_GRAPHICS_CONNECT)
var _VIR_DOMAIN_EVENT_GRAPHICS_INITIALIZE_INT = int(VIR_DOMAIN_EVENT_GRAPHICS_INITIALIZE)
var _VIR_DOMAIN_EVENT_GRAPHICS_DISCONNECT_INT = int(VIR_DOMAIN_EVENT_GRAPHICS_DISCONNECT)
var _VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV4_INT = int(VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV4)
var _VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV6_INT = int(VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV6)
var _VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_UNIX_INT = int(VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_UNIX)
var _VIR_DOMAIN_BLOCK_JOB_TYPE_UNKNOWN_INT = int(VIR_DOMAIN_BLOCK_JOB_TYPE_UNKNOWN)
var _VIR_DOMAIN_BLOCK_JOB_TYPE_PULL_INT = int(VIR_DOMAIN_BLOCK_JOB_TYPE_PULL)
var _VIR_DOMAIN_BLOCK_JOB_TYPE_COPY_INT = int(VIR_DOMAIN_BLOCK_JOB_TYPE_COPY)
var _VIR_DOMAIN_BLOCK_JOB_TYPE_COMMIT_INT = int(VIR_DOMAIN_BLOCK_JOB_TYPE_COMMIT)
var _VIR_DOMAIN_BLOCK_JOB_COMPLETED_INT = int(VIR_DOMAIN_BLOCK_JOB_COMPLETED)
var _VIR_DOMAIN_BLOCK_JOB_FAILED_INT = int(VIR_DOMAIN_BLOCK_JOB_FAILED)
var _VIR_DOMAIN_BLOCK_JOB_CANCELED_INT = int(VIR_DOMAIN_BLOCK_JOB_CANCELED)
var _VIR_DOMAIN_BLOCK_JOB_READY_INT = int(VIR_DOMAIN_BLOCK_JOB_READY)
var _VIR_DOMAIN_EVENT_DISK_CHANGE_MISSING_ON_START_INT = int(VIR_DOMAIN_EVENT_DISK_CHANGE_MISSING_ON_START)
var _VIR_DOMAIN_EVENT_DISK_DROP_MISSING_ON_START_INT = int(VIR_DOMAIN_EVENT_DISK_DROP_MISSING_ON_START)
var _VIR_DOMAIN_EVENT_TRAY_CHANGE_OPEN_INT = int(VIR_DOMAIN_EVENT_TRAY_CHANGE_OPEN)
var _VIR_DOMAIN_EVENT_TRAY_CHANGE_CLOSE_INT = int(VIR_DOMAIN_EVENT_TRAY_CHANGE_CLOSE)
var _VIR_DOMAIN_RUNNING_UNKNOWN_INT = int(VIR_DOMAIN_RUNNING_UNKNOWN)
var _VIR_DOMAIN_RUNNING_BOOTED_INT = int(VIR_DOMAIN_RUNNING_BOOTED)
var _VIR_DOMAIN_RUNNING_MIGRATED_INT = int(VIR_DOMAIN_RUNNING_MIGRATED)
var _VIR_DOMAIN_RUNNING_RESTORED_INT = int(VIR_DOMAIN_RUNNING_RESTORED)
var _VIR_DOMAIN_RUNNING_FROM_SNAPSHOT_INT = int(VIR_DOMAIN_RUNNING_FROM_SNAPSHOT)
var _VIR_DOMAIN_RUNNING_UNPAUSED_INT = int(VIR_DOMAIN_RUNNING_UNPAUSED)
var _VIR_DOMAIN_RUNNING_MIGRATION_CANCELED_INT = int(VIR_DOMAIN_RUNNING_MIGRATION_CANCELED)
var _VIR_DOMAIN_RUNNING_SAVE_CANCELED_INT = int(VIR_DOMAIN_RUNNING_SAVE_CANCELED)
var _VIR_DOMAIN_RUNNING_WAKEUP_INT = int(VIR_DOMAIN_RUNNING_WAKEUP)
var _VIR_DOMAIN_RUNNING_CRASHED_INT = int(VIR_DOMAIN_RUNNING_CRASHED)
var _VIR_DOMAIN_PAUSED_UNKNOWN_INT = int(VIR_DOMAIN_PAUSED_UNKNOWN)
var _VIR_DOMAIN_PAUSED_USER_INT = int(VIR_DOMAIN_PAUSED_USER)
var _VIR_DOMAIN_PAUSED_MIGRATION_INT = int(VIR_DOMAIN_PAUSED_MIGRATION)
var _VIR_DOMAIN_PAUSED_SAVE_INT = int(VIR_DOMAIN_PAUSED_SAVE)
var _VIR_DOMAIN_PAUSED_DUMP_INT = int(VIR_DOMAIN_PAUSED_DUMP)
var _VIR_DOMAIN_PAUSED_IOERROR_INT = int(VIR_DOMAIN_PAUSED_IOERROR)
var _VIR_DOMAIN_PAUSED_WATCHDOG_INT = int(VIR_DOMAIN_PAUSED_WATCHDOG)
var _VIR_DOMAIN_PAUSED_FROM_SNAPSHOT_INT = int(VIR_DOMAIN_PAUSED_FROM_SNAPSHOT)
var _VIR_DOMAIN_PAUSED_SHUTTING_DOWN_INT = int(VIR_DOMAIN_PAUSED_SHUTTING_DOWN)
var _VIR_DOMAIN_PAUSED_SNAPSHOT_INT = int(VIR_DOMAIN_PAUSED_SNAPSHOT)
var _VIR_DOMAIN_PAUSED_CRASHED_INT = int(VIR_DOMAIN_PAUSED_CRASHED)
var _VIR_DOMAIN_XML_SECURE_INT = int(VIR_DOMAIN_XML_SECURE)
var _VIR_DOMAIN_XML_INACTIVE_INT = int(VIR_DOMAIN_XML_INACTIVE)
var _VIR_DOMAIN_XML_UPDATE_CPU_INT = int(VIR_DOMAIN_XML_UPDATE_CPU)
var _VIR_DOMAIN_XML_MIGRATABLE_INT = int(VIR_DOMAIN_XML_MIGRATABLE)
var _VIR_DOMAIN_QEMU_MONITOR_COMMAND_DEFAULT_INT = int(VIR_DOMAIN_QEMU_MONITOR_COMMAND_DEFAULT)
var _VIR_DOMAIN_QEMU_MONITOR_COMMAND_HMP_INT = int(VIR_DOMAIN_QEMU_MONITOR_COMMAND_HMP)
var _VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE_INT = int(VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE)
var _VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENT_INT = int(VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENT)
var _VIR_IP_ADDR_TYPE_IPV4_INT = int(VIR_IP_ADDR_TYPE_IPV4)
var _VIR_IP_ADDR_TYPE_IPV6_INT = int(VIR_IP_ADDR_TYPE_IPV6)

var _s_map = map[int]string{
	_VIR_DOMAIN_NOSTATE_INT:                            _s_name[0:18],
	_VIR_DOMAIN_RUNNING_INT:                            _s_name[18:36],
	_VIR_DOMAIN_BLOCKED_INT:                            _s_name[36:54],
	_VIR_DOMAIN_PAUSED_INT:                             _s_name[54:71],
	_VIR_DOMAIN_SHUTDOWN_INT:                           _s_name[71:90],
	_VIR_DOMAIN_CRASHED_INT:                            _s_name[90:108],
	_VIR_DOMAIN_PMSUSPENDED_INT:                        _s_name[108:130],
	_VIR_DOMAIN_SHUTOFF_INT:                            _s_name[130:148],
	_VIR_VCPU_OFFLINE_INT:                              _s_name[148:164],
	_VIR_VCPU_RUNNING_INT:                              _s_name[164:180],
	_VIR_VCPU_BLOCKED_INT:                              _s_name[180:196],
	_VIR_CONNECT_LIST_DOMAINS_ACTIVE_INT:               _s_name[196:227],
	_VIR_CONNECT_LIST_DOMAINS_INACTIVE_INT:             _s_name[227:260],
	_VIR_CONNECT_LIST_DOMAINS_PERSISTENT_INT:           _s_name[260:295],
	_VIR_CONNECT_LIST_DOMAINS_TRANSIENT_INT:            _s_name[295:329],
	_VIR_CONNECT_LIST_DOMAINS_RUNNING_INT:              _s_name[329:361],
	_VIR_CONNECT_LIST_DOMAINS_PAUSED_INT:               _s_name[361:392],
	_VIR_CONNECT_LIST_DOMAINS_SHUTOFF_INT:              _s_name[392:424],
	_VIR_CONNECT_LIST_DOMAINS_OTHER_INT:                _s_name[424:454],
	_VIR_CONNECT_LIST_DOMAINS_MANAGEDSAVE_INT:          _s_name[454:490],
	_VIR_CONNECT_LIST_DOMAINS_NO_MANAGEDSAVE_INT:       _s_name[490:529],
	_VIR_CONNECT_LIST_DOMAINS_AUTOSTART_INT:            _s_name[529:563],
	_VIR_CONNECT_LIST_DOMAINS_NO_AUTOSTART_INT:         _s_name[563:600],
	_VIR_CONNECT_LIST_DOMAINS_HAS_SNAPSHOT_INT:         _s_name[600:637],
	_VIR_CONNECT_LIST_DOMAINS_NO_SNAPSHOT_INT:          _s_name[637:673],
	_VIR_DOMAIN_METADATA_DESCRIPTION_INT:               _s_name[673:704],
	_VIR_DOMAIN_METADATA_TITLE_INT:                     _s_name[704:729],
	_VIR_DOMAIN_METADATA_ELEMENT_INT:                   _s_name[729:756],
	_VIR_DOMAIN_VCPU_CONFIG_INT:                        _s_name[756:778],
	_VIR_DOMAIN_VCPU_CURRENT_INT:                       _s_name[778:801],
	_VIR_DOMAIN_VCPU_LIVE_INT:                          _s_name[801:821],
	_VIR_DOMAIN_VCPU_MAXIMUM_INT:                       _s_name[821:844],
	_VIR_DOMAIN_VCPU_GUEST_INT:                         _s_name[844:865],
	_VIR_DOMAIN_AFFECT_CONFIG_INT:                      _s_name[865:889],
	_VIR_DOMAIN_AFFECT_CURRENT_INT:                     _s_name[889:914],
	_VIR_DOMAIN_AFFECT_LIVE_INT:                        _s_name[914:936],
	_VIR_DOMAIN_MEM_CONFIG_INT:                         _s_name[936:957],
	_VIR_DOMAIN_MEM_CURRENT_INT:                        _s_name[957:979],
	_VIR_DOMAIN_MEM_LIVE_INT:                           _s_name[979:998],
	_VIR_DOMAIN_MEM_MAXIMUM_INT:                        _s_name[998:1020],
	_VIR_STORAGE_POOL_INACTIVE_INT:                     _s_name[1020:1045],
	_VIR_STORAGE_POOL_BUILDING_INT:                     _s_name[1045:1070],
	_VIR_STORAGE_POOL_RUNNING_INT:                      _s_name[1070:1094],
	_VIR_STORAGE_POOL_DEGRADED_INT:                     _s_name[1094:1119],
	_VIR_STORAGE_POOL_INACCESSIBLE_INT:                 _s_name[1119:1148],
	_VIR_STORAGE_POOL_BUILD_NEW_INT:                    _s_name[1148:1174],
	_VIR_STORAGE_POOL_BUILD_REPAIR_INT:                 _s_name[1174:1203],
	_VIR_STORAGE_POOL_BUILD_RESIZE_INT:                 _s_name[1203:1232],
	_VIR_STORAGE_POOL_BUILD_NO_OVERWRITE_INT:           _s_name[1232:1267],
	_VIR_STORAGE_POOL_BUILD_OVERWRITE_INT:              _s_name[1267:1299],
	_VIR_DOMAIN_DESTROY_DEFAULT_INT:                    _s_name[1299:1325],
	_VIR_DOMAIN_DESTROY_GRACEFUL_INT:                   _s_name[1325:1352],
	_VIR_DOMAIN_SHUTDOWN_DEFAULT_INT:                   _s_name[1352:1379],
	_VIR_DOMAIN_SHUTDOWN_ACPI_POWER_BTN_INT:            _s_name[1379:1413],
	_VIR_DOMAIN_SHUTDOWN_GUEST_AGENT_INT:               _s_name[1413:1444],
	_VIR_DOMAIN_SHUTDOWN_INITCTL_INT:                   _s_name[1444:1471],
	_VIR_DOMAIN_SHUTDOWN_SIGNAL_INT:                    _s_name[1471:1497],
	_VIR_DOMAIN_DEVICE_MODIFY_CONFIG_INT:               _s_name[1497:1528],
	_VIR_DOMAIN_DEVICE_MODIFY_CURRENT_INT:              _s_name[1528:1560],
	_VIR_DOMAIN_DEVICE_MODIFY_LIVE_INT:                 _s_name[1560:1589],
	_VIR_DOMAIN_DEVICE_MODIFY_FORCE_INT:                _s_name[1589:1619],
	_VIR_STORAGE_VOL_CREATE_PREALLOC_METADATA_INT:      _s_name[1619:1659],
	_VIR_STORAGE_VOL_DELETE_NORMAL_INT:                 _s_name[1659:1688],
	_VIR_STORAGE_VOL_DELETE_ZEROED_INT:                 _s_name[1688:1717],
	_VIR_STORAGE_VOL_RESIZE_ALLOCATE_INT:               _s_name[1717:1748],
	_VIR_STORAGE_VOL_RESIZE_DELTA_INT:                  _s_name[1748:1776],
	_VIR_STORAGE_VOL_RESIZE_SHRINK_INT:                 _s_name[1776:1805],
	_VIR_STORAGE_VOL_FILE_INT:                          _s_name[1805:1825],
	_VIR_STORAGE_VOL_BLOCK_INT:                         _s_name[1825:1846],
	_VIR_STORAGE_VOL_DIR_INT:                           _s_name[1846:1865],
	_VIR_STORAGE_VOL_NETWORK_INT:                       _s_name[1865:1888],
	_VIR_STORAGE_VOL_NETDIR_INT:                        _s_name[1888:1910],
	_VIR_STORAGE_VOL_WIPE_ALG_ZERO_INT:                 _s_name[1910:1939],
	_VIR_STORAGE_VOL_WIPE_ALG_NNSA_INT:                 _s_name[1939:1968],
	_VIR_STORAGE_VOL_WIPE_ALG_DOD_INT:                  _s_name[1968:1996],
	_VIR_STORAGE_VOL_WIPE_ALG_BSI_INT:                  _s_name[1996:2024],
	_VIR_STORAGE_VOL_WIPE_ALG_GUTMANN_INT:              _s_name[2024:2056],
	_VIR_STORAGE_VOL_WIPE_ALG_SCHNEIER_INT:             _s_name[2056:2089],
	_VIR_STORAGE_VOL_WIPE_ALG_PFITZNER7_INT:            _s_name[2089:2123],
	_VIR_STORAGE_VOL_WIPE_ALG_PFITZNER33_INT:           _s_name[2123:2158],
	_VIR_STORAGE_VOL_WIPE_ALG_RANDOM_INT:               _s_name[2158:2189],
	_VIR_SECRET_USAGE_TYPE_NONE_INT:                    _s_name[2189:2215],
	_VIR_SECRET_USAGE_TYPE_VOLUME_INT:                  _s_name[2215:2243],
	_VIR_SECRET_USAGE_TYPE_CEPH_INT:                    _s_name[2243:2269],
	_VIR_SECRET_USAGE_TYPE_ISCSI_INT:                   _s_name[2269:2296],
	_VIR_CONNECT_LIST_NETWORKS_INACTIVE_INT:            _s_name[2296:2330],
	_VIR_CONNECT_LIST_NETWORKS_ACTIVE_INT:              _s_name[2330:2362],
	_VIR_CONNECT_LIST_NETWORKS_PERSISTENT_INT:          _s_name[2362:2398],
	_VIR_CONNECT_LIST_NETWORKS_TRANSIENT_INT:           _s_name[2398:2433],
	_VIR_CONNECT_LIST_NETWORKS_AUTOSTART_INT:           _s_name[2433:2468],
	_VIR_CONNECT_LIST_NETWORKS_NO_AUTOSTART_INT:        _s_name[2468:2506],
	_VIR_CONNECT_LIST_STORAGE_POOLS_INACTIVE_INT:       _s_name[2506:2545],
	_VIR_CONNECT_LIST_STORAGE_POOLS_ACTIVE_INT:         _s_name[2545:2582],
	_VIR_CONNECT_LIST_STORAGE_POOLS_PERSISTENT_INT:     _s_name[2582:2623],
	_VIR_CONNECT_LIST_STORAGE_POOLS_TRANSIENT_INT:      _s_name[2623:2663],
	_VIR_CONNECT_LIST_STORAGE_POOLS_AUTOSTART_INT:      _s_name[2663:2703],
	_VIR_CONNECT_LIST_STORAGE_POOLS_NO_AUTOSTART_INT:   _s_name[2703:2746],
	_VIR_CONNECT_LIST_STORAGE_POOLS_DIR_INT:            _s_name[2746:2780],
	_VIR_CONNECT_LIST_STORAGE_POOLS_FS_INT:             _s_name[2780:2813],
	_VIR_CONNECT_LIST_STORAGE_POOLS_NETFS_INT:          _s_name[2813:2849],
	_VIR_CONNECT_LIST_STORAGE_POOLS_LOGICAL_INT:        _s_name[2849:2887],
	_VIR_CONNECT_LIST_STORAGE_POOLS_DISK_INT:           _s_name[2887:2922],
	_VIR_CONNECT_LIST_STORAGE_POOLS_ISCSI_INT:          _s_name[2922:2958],
	_VIR_CONNECT_LIST_STORAGE_POOLS_SCSI_INT:           _s_name[2958:2993],
	_VIR_CONNECT_LIST_STORAGE_POOLS_MPATH_INT:          _s_name[2993:3029],
	_VIR_CONNECT_LIST_STORAGE_POOLS_RBD_INT:            _s_name[3029:3063],
	_VIR_CONNECT_LIST_STORAGE_POOLS_SHEEPDOG_INT:       _s_name[3063:3102],
	_VIR_CONNECT_LIST_STORAGE_POOLS_GLUSTER_INT:        _s_name[3102:3140],
	_VIR_STREAM_NONBLOCK_INT:                           _s_name[3140:3159],
	_VIR_KEYCODE_SET_LINUX_INT:                         _s_name[3159:3180],
	_VIR_KEYCODE_SET_XT_INT:                            _s_name[3180:3198],
	_VIR_KEYCODE_SET_ATSET1_INT:                        _s_name[3198:3220],
	_VIR_KEYCODE_SET_ATSET2_INT:                        _s_name[3220:3242],
	_VIR_KEYCODE_SET_ATSET3_INT:                        _s_name[3242:3264],
	_VIR_KEYCODE_SET_OSX_INT:                           _s_name[3264:3283],
	_VIR_KEYCODE_SET_XT_KBD_INT:                        _s_name[3283:3305],
	_VIR_KEYCODE_SET_USB_INT:                           _s_name[3305:3324],
	_VIR_KEYCODE_SET_WIN32_INT:                         _s_name[3324:3345],
	_VIR_KEYCODE_SET_RFB_INT:                           _s_name[3345:3364],
	_VIR_DOMAIN_NONE_INT:                               _s_name[3364:3379],
	_VIR_DOMAIN_START_PAUSED_INT:                       _s_name[3379:3402],
	_VIR_DOMAIN_START_AUTODESTROY_INT:                  _s_name[3402:3430],
	_VIR_DOMAIN_START_BYPASS_CACHE_INT:                 _s_name[3430:3459],
	_VIR_DOMAIN_START_FORCE_BOOT_INT:                   _s_name[3459:3486],
	_VIR_DOMAIN_MEMORY_PARAM_UNLIMITED_INT:             _s_name[3486:3519],
	_VIR_DOMAIN_EVENT_ID_LIFECYCLE_INT:                 _s_name[3519:3548],
	_VIR_DOMAIN_EVENT_ID_REBOOT_INT:                    _s_name[3548:3574],
	_VIR_DOMAIN_EVENT_ID_RTC_CHANGE_INT:                _s_name[3574:3604],
	_VIR_DOMAIN_EVENT_ID_WATCHDOG_INT:                  _s_name[3604:3632],
	_VIR_DOMAIN_EVENT_ID_IO_ERROR_INT:                  _s_name[3632:3660],
	_VIR_DOMAIN_EVENT_ID_GRAPHICS_INT:                  _s_name[3660:3688],
	_VIR_DOMAIN_EVENT_ID_IO_ERROR_REASON_INT:           _s_name[3688:3723],
	_VIR_DOMAIN_EVENT_ID_CONTROL_ERROR_INT:             _s_name[3723:3756],
	_VIR_DOMAIN_EVENT_ID_BLOCK_JOB_INT:                 _s_name[3756:3785],
	_VIR_DOMAIN_EVENT_ID_DISK_CHANGE_INT:               _s_name[3785:3816],
	_VIR_DOMAIN_EVENT_ID_TRAY_CHANGE_INT:               _s_name[3816:3847],
	_VIR_DOMAIN_EVENT_ID_PMWAKEUP_INT:                  _s_name[3847:3875],
	_VIR_DOMAIN_EVENT_ID_PMSUSPEND_INT:                 _s_name[3875:3904],
	_VIR_DOMAIN_EVENT_ID_BALLOON_CHANGE_INT:            _s_name[3904:3938],
	_VIR_DOMAIN_EVENT_ID_PMSUSPEND_DISK_INT:            _s_name[3938:3972],
	_VIR_DOMAIN_EVENT_ID_DEVICE_REMOVED_INT:            _s_name[3972:4006],
	_VIR_DOMAIN_EVENT_DEFINED_INT:                      _s_name[4006:4030],
	_VIR_DOMAIN_EVENT_UNDEFINED_INT:                    _s_name[4030:4056],
	_VIR_DOMAIN_EVENT_STARTED_INT:                      _s_name[4056:4080],
	_VIR_DOMAIN_EVENT_SUSPENDED_INT:                    _s_name[4080:4106],
	_VIR_DOMAIN_EVENT_RESUMED_INT:                      _s_name[4106:4130],
	_VIR_DOMAIN_EVENT_STOPPED_INT:                      _s_name[4130:4154],
	_VIR_DOMAIN_EVENT_SHUTDOWN_INT:                     _s_name[4154:4179],
	_VIR_DOMAIN_EVENT_PMSUSPENDED_INT:                  _s_name[4179:4207],
	_VIR_DOMAIN_EVENT_CRASHED_INT:                      _s_name[4207:4231],
	_VIR_DOMAIN_EVENT_WATCHDOG_NONE_INT:                _s_name[4231:4261],
	_VIR_DOMAIN_EVENT_WATCHDOG_PAUSE_INT:               _s_name[4261:4292],
	_VIR_DOMAIN_EVENT_WATCHDOG_RESET_INT:               _s_name[4292:4323],
	_VIR_DOMAIN_EVENT_WATCHDOG_POWEROFF_INT:            _s_name[4323:4357],
	_VIR_DOMAIN_EVENT_WATCHDOG_SHUTDOWN_INT:            _s_name[4357:4391],
	_VIR_DOMAIN_EVENT_WATCHDOG_DEBUG_INT:               _s_name[4391:4422],
	_VIR_DOMAIN_EVENT_IO_ERROR_NONE_INT:                _s_name[4422:4452],
	_VIR_DOMAIN_EVENT_IO_ERROR_PAUSE_INT:               _s_name[4452:4483],
	_VIR_DOMAIN_EVENT_IO_ERROR_REPORT_INT:              _s_name[4483:4515],
	_VIR_DOMAIN_EVENT_GRAPHICS_CONNECT_INT:             _s_name[4515:4548],
	_VIR_DOMAIN_EVENT_GRAPHICS_INITIALIZE_INT:          _s_name[4548:4584],
	_VIR_DOMAIN_EVENT_GRAPHICS_DISCONNECT_INT:          _s_name[4584:4620],
	_VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV4_INT:        _s_name[4620:4658],
	_VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV6_INT:        _s_name[4658:4696],
	_VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_UNIX_INT:        _s_name[4696:4734],
	_VIR_DOMAIN_BLOCK_JOB_TYPE_UNKNOWN_INT:             _s_name[4734:4767],
	_VIR_DOMAIN_BLOCK_JOB_TYPE_PULL_INT:                _s_name[4767:4797],
	_VIR_DOMAIN_BLOCK_JOB_TYPE_COPY_INT:                _s_name[4797:4827],
	_VIR_DOMAIN_BLOCK_JOB_TYPE_COMMIT_INT:              _s_name[4827:4859],
	_VIR_DOMAIN_BLOCK_JOB_COMPLETED_INT:                _s_name[4859:4889],
	_VIR_DOMAIN_BLOCK_JOB_FAILED_INT:                   _s_name[4889:4916],
	_VIR_DOMAIN_BLOCK_JOB_CANCELED_INT:                 _s_name[4916:4945],
	_VIR_DOMAIN_BLOCK_JOB_READY_INT:                    _s_name[4945:4971],
	_VIR_DOMAIN_EVENT_DISK_CHANGE_MISSING_ON_START_INT: _s_name[4971:5016],
	_VIR_DOMAIN_EVENT_DISK_DROP_MISSING_ON_START_INT:   _s_name[5016:5059],
	_VIR_DOMAIN_EVENT_TRAY_CHANGE_OPEN_INT:             _s_name[5059:5092],
	_VIR_DOMAIN_EVENT_TRAY_CHANGE_CLOSE_INT:            _s_name[5092:5126],
	_VIR_DOMAIN_RUNNING_UNKNOWN_INT:                    _s_name[5126:5152],
	_VIR_DOMAIN_RUNNING_BOOTED_INT:                     _s_name[5152:5177],
	_VIR_DOMAIN_RUNNING_MIGRATED_INT:                   _s_name[5177:5204],
	_VIR_DOMAIN_RUNNING_RESTORED_INT:                   _s_name[5204:5231],
	_VIR_DOMAIN_RUNNING_FROM_SNAPSHOT_INT:              _s_name[5231:5263],
	_VIR_DOMAIN_RUNNING_UNPAUSED_INT:                   _s_name[5263:5290],
	_VIR_DOMAIN_RUNNING_MIGRATION_CANCELED_INT:         _s_name[5290:5327],
	_VIR_DOMAIN_RUNNING_SAVE_CANCELED_INT:              _s_name[5327:5359],
	_VIR_DOMAIN_RUNNING_WAKEUP_INT:                     _s_name[5359:5384],
	_VIR_DOMAIN_RUNNING_CRASHED_INT:                    _s_name[5384:5410],
	_VIR_DOMAIN_PAUSED_UNKNOWN_INT:                     _s_name[5410:5435],
	_VIR_DOMAIN_PAUSED_USER_INT:                        _s_name[5435:5457],
	_VIR_DOMAIN_PAUSED_MIGRATION_INT:                   _s_name[5457:5484],
	_VIR_DOMAIN_PAUSED_SAVE_INT:                        _s_name[5484:5506],
	_VIR_DOMAIN_PAUSED_DUMP_INT:                        _s_name[5506:5528],
	_VIR_DOMAIN_PAUSED_IOERROR_INT:                     _s_name[5528:5553],
	_VIR_DOMAIN_PAUSED_WATCHDOG_INT:                    _s_name[5553:5579],
	_VIR_DOMAIN_PAUSED_FROM_SNAPSHOT_INT:               _s_name[5579:5610],
	_VIR_DOMAIN_PAUSED_SHUTTING_DOWN_INT:               _s_name[5610:5641],
	_VIR_DOMAIN_PAUSED_SNAPSHOT_INT:                    _s_name[5641:5667],
	_VIR_DOMAIN_PAUSED_CRASHED_INT:                     _s_name[5667:5692],
	_VIR_DOMAIN_XML_SECURE_INT:                         _s_name[5692:5713],
	_VIR_DOMAIN_XML_INACTIVE_INT:                       _s_name[5713:5736],
	_VIR_DOMAIN_XML_UPDATE_CPU_INT:                     _s_name[5736:5761],
	_VIR_DOMAIN_XML_MIGRATABLE_INT:                     _s_name[5761:5786],
	_VIR_DOMAIN_QEMU_MONITOR_COMMAND_DEFAULT_INT:       _s_name[5786:5825],
	_VIR_DOMAIN_QEMU_MONITOR_COMMAND_HMP_INT:           _s_name[5825:5860],
	_VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE_INT:      _s_name[5860:5900],
	_VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENT_INT:      _s_name[5900:5940],
	_VIR_IP_ADDR_TYPE_IPV4_INT:                         _s_name[5940:5961],
	_VIR_IP_ADDR_TYPE_IPV6_INT:                         _s_name[5961:5982],
}

func ConstToString(i int) string {
	if str, ok := _s_map[i]; ok {
		return str
	}
	return fmt.Sprintf("%v", i)
}
